### ISSUE TITLE
Support multiple projections in the map

### ISSUE THREAD

**Issue by CptSchnitz** [MapColonies/shared-components-deprecated#43]
Right now the map is hard coded to work with WGS84 (EPSG:4326). We would like this option to be configurable to support other projections like Web mercator (EPSG:3857).

**Comment by syncush** [comment]
@alebinson, @asafMasa the priority for this feature is high

**Comment by CptSchnitz** [comment]
blocks #39

**Comment by alebinson** [comment]
Looks good, make it parametrized. Do you need my help?

**Comment by CptSchnitz** [comment]
We need to make sure how they change affects other parts of the map, like layer projection, the mouse position control, and other places.
I will need your help with testing how the changes affect the components you wrote (wms, wmts).
